service: financee-api
# app and org for use with dashboard.serverless.com
app: financee-api
org: marcusfonseca

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    MARCUS_TEST: ${env:MARCUS_TEST}

functions:
  user:
    handler: src/routes/users.handler
    events:
      - http:
          path: /users
          method: ANY
      - http:
          path: /users/{proxy+}
          method: ANY
  team:
    handler: src/routes/teams.handler
    events:
      - http:
          path: /teams
          method: ANY
      - http:
          path: /teams/{proxy+}
          method: ANY

plugins:
  - serverless-offline
  - serverless-dotenv-plugin