service: financee-api
# app and org for use with dashboard.serverless.com
app: financee-api
org: marcusfonseca

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    MARCUS_TEST: ${env:MARCUS_TEST}

functions:
  category:
    handler: src/routes/category.handler
    events:
      - http:
          path: /category
          method: ANY
      - http:
          path: /category/{proxy+}
          method: ANY

plugins:
  - serverless-offline
  - serverless-dotenv-plugin