service: financee-api
# app and org for use with dashboard.serverless.com
app: financee-api
org: marcusfonseca

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    MARCUS_TEST: ${env:MARCUS_TEST}

functions:
  user:
    handler: src/routes/users.handler
    events:
      - http:
          path: /users
          method: ANY
      - http:
          path: /users/{proxy+}
          method: ANY
  team:
    handler: src/routes/teams.handler
    events:
      - http:
          path: /teams
          method: ANY
      - http:
          path: /teams/{proxy+}
          method: ANY
  account:
    handler: src/routes/accounts.handler
    events:
      - http:
          path: /accounts
          method: ANY
      - http:
          path: /accounts/{proxy+}
          method: ANY
  statuses:
    handler: src/routes/transactionStatuses.handler
    events:
      - http:
          path: /statuses
          method: ANY
      - http:
          path: /statuses/{proxy+}
          method: ANY
  types:
      handler: src/routes/transactionTypes.handler
      events:
        - http:
            path: /types
            method: ANY
        - http:
            path: /types/{proxy+}
            method: ANY
  categories:
      handler: src/routes/categories.handler
      events:
        - http:
            path: /categories
            method: ANY
        - http:
            path: /categories/{proxy+}
            method: ANY

plugins:
  - serverless-offline
  - serverless-dotenv-plugin